### ISSUE TITLE
Doesn't work on newer versions of Python

### ISSUE THREAD

**Issue by bryanhpchiang** [JJTech0130/pypush#28]
```
(base) bryan@Bryans-MacBook-Pro-7 pypush % python3 demo.py
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    import apns
  File "/Users/bryan/work/pypush/apns.py", line 12, in <module>
    import tlslite
  File "/Users/bryan/miniconda3/lib/python3.8/site-packages/tlslite/__init__.py", line 27, in <module>
    from tlslite.api import *
  File "/Users/bryan/miniconda3/lib/python3.8/site-packages/tlslite/api.py", line 11, in <module>
    from .tlsconnection import TLSConnection
  File "/Users/bryan/miniconda3/lib/python3.8/site-packages/tlslite/tlsconnection.py", line 71
    async=False):
    ^
SyntaxError: invalid syntax
```

**Comment by JJTech0130** [comment]
~~It should definitely work in 3.8, in fact 3.10 is the minimum. Make sure that you installed tlslite-ng with the requirements.txt, it's pinned to a specific version that works.~~
**EDIT:** I have no idea how I misread that, anyway, 3.8 is too *old*, 3.10 is the minimum version supported. So this is not planned to work.

**Comment by bryanhpchiang** [comment]
Still doesn't work with 3.10:

```
(turbo) bryan@Bryans-MacBook-Pro-7 pypush % python demo.py
Traceback (most recent call last):
  File "/Users/bryan/work/pypush/demo.py", line 13, in <module>
    import apns
  File "/Users/bryan/work/pypush/apns.py", line 12, in <module>
    import tlslite
  File "/Users/bryan/miniconda3/envs/turbo/lib/python3.10/site-packages/tlslite/__init__.py", line 27, in <module>
    from tlslite.api import *
  File "/Users/bryan/miniconda3/envs/turbo/lib/python3.10/site-packages/tlslite/api.py", line 11, in <module>
    from .tlsconnection import TLSConnection
  File "/Users/bryan/miniconda3/envs/turbo/lib/python3.10/site-packages/tlslite/tlsconnection.py", line 71
    async=False):
    ^^^^^
SyntaxError: invalid syntax
```

**Comment by JJTech0130** [comment]
Are you sure you installed the correct version of tlslite-ng? The requirements.txt is pinned to a prerelease version for a reason.

**Comment by bryanhpchiang** [comment]
Resolved with requirements.txt

**Comment by bryanhpchiang** [comment]
Thanks!

**Comment by CoolCat467** [comment]
Doesn't work on python 3.12 without other dependencies, `asyncore` is no longer shipped in the standard library anymore and you have to install `pyasyncore` (https://pypi.org/project/pyasyncore/)
